blog/urls.py
from django.urls import path,include
from blog import views
from django.contrib import admin

app_name = '<blog>'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
    path('about/',views.about,name="about"),
    path('users/',views.users,name="users"),
    path('macro/',views.macro,name="macro"),
    path('earth/',views.earth,name="earth"),
    path('archi/',views.archi,name="archi"),
    path('animals/',views.animals,name="animals"),
    path('travel/',views.travel,name="travel"),
    path('long/',views.long,name="long"),
    path('roads/',views.roads,name="roads"),
    path('experiment/',views.experiment,name="experiment"),





]

mystockweb/urls.py
from django.contrib import admin
from django.urls import path,include
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.index,name='index'),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
    path('admin/', admin.site.urls),
    path('special/', views.special,name='special'),
    path('logout/', views.user_logout, name='logout'),
    path('admin/',views.about,name='admin'),
    path('macro/',views.macro,name="macro"),


]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# SuperUserInformation
# User: Jose
# Email: training@pieriandata.com
# Password: testpassword

# Create your models here.




class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Add any additional attributes you want
    portfolio_site = models.URLField(blank=True)
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option="build_ext" --global-option="--disable-jpeg"
    profile_pic = models.ImageField(upload_to='blog/profile_pics',blank=True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username
class Feedback(models.Model):
    name = models.CharField(max_length=128)
    email = models.EmailField(max_length=254)
    feedback = models.TextField(max_length=500)

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo,Feedback
from django.forms import ModelForm

class UserForm(forms.ModelForm):
     password = forms.CharField(widget=forms.PasswordInput())

     class Meta():
         model = User
         fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('portfolio_site','profile_pic')

class FeedbackForm(forms.ModelForm):
    class Meta():
        model = Feedback
        fields =  '__all__'

blog/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .forms import UserForm,UserProfileInfoForm,FeedbackForm


# Create your views here.


def macro(request):
    return render(request,'blog/macro.html')
def earth(request):
    return render(request,'blog/earth.html')
def archi(request):
    return render(request,'blog/archi.html')
def animals(request):
    return render(request,'blog/animals.html')
def travel(request):
    return render(request,'blog/travel.html')
def long(request):
    return render(request,'blog/long.html')
def roads(request):
    return render(request,'blog/roads.html')
def experiment(request):
    return render(request,'blog/experiment.html')
# Extra Imports for the Login and Logout Capabilities
def users(request):
    form = FeedbackForm()
    if request.method == 'POST':
        print(request.POST)
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return HttpResponseRedirect('/about/')
        else:
            print("invalid")
            form = FeedbackForm()
    return render(request,'blog/users.html',{'form':form})


def about(request):
    return render(request,'blog/about.html')
# Create your views here.
def index(request):
    return render(request,'blog/index.html')

@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in. Nice!")

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'blog/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'blog/login.html', {})

blog/templates/blog/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>About</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,700|Merriweather' rel='stylesheet' type='text/css'>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Teko:wght@600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/about.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Teko:wght@600&display=swap" rel="stylesheet">

  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index' %}">My Stock</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'admin:index' %}">Admin <span class="sr-only"></span></a></li>
        <li><a href="{% url 'blog:users' %}">Feedback</a></li>
        <li><a href="{% url 'blog:register' %}">Register</a></li>
        <li><a href="{% url 'blog:about' %}">About</a></li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li><a href="{% url 'logout' %}"><span id="username">{{ user.username }} </span>   Logout</a></li>
        {% else %}
        <li><a href="{% url 'blog:user_login' %}">Login</a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div id="main1">


    <section class="about">
      <div class="main">
        <img src="{% static 'images/about/about.jpg' %}" alt="">
        <div class="about-text">
          <h1>About Me</h1>
          <h5>Student <span class='learn' >& Learner</span> </h5>
          <p>I am a student who is enthusiastic about learning new things in the field of Web Development and python coding. My Plan is to work on a project related to Machine Learning and Deep Learning. I am a Photographer by hobby and I prefer capturing Macro and Travel Photographs</p>
          <button class="GFG"
    onclick="window.location.href = 'https://wa.me/+919591999217';">
        Let's Talk
    </button>

        </div>
      </div>
    </section>
    </div>
  </body>
</html>

blog/templates/blog/animals.html
<!doctype html>
{% load static %}
<html lang="en">
 <head>
  <meta charset="utf-8">

  <title>Image Gallery</title>
  <meta name="description" content="Responsive Image Gallery">
  <meta name="author" content="Tim Wells">
  <link rel="stylesheet" href="{% static 'css/macro.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

  <style type="text/css">
  </style>
</head>
<body>

  <div class="whole">



    <nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index' %}"> <span id="my">My</span> Stock</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'admin:index' %}">Admin <span class="sr-only"></span></a></li>
        <li><a href="{% url 'blog:users' %}">Feedback</a></li>
        <li><a href="{% url 'blog:register' %}">Register</a></li>
        <li><a href="{% url 'blog:about' %}">About</a></li>



      </ul>
      <ul class="nav navbar-nav navbar-right">


        {% if user.is_authenticated %}
        <li><a href="{% url 'logout' %}"><span id="username">{{ user.username }} </span>   Logout</a></li>
        {% else %}
        <li><a href="{% url 'blog:user_login' %}"><span id="login">Login</span></a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  </nav>


<div id = "items">


<div id="gallery">


    <img src="{% static 'images/animals/image1.jpg' %}">
    <img src="{% static 'images/animals/image2.jpg' %}">
    <img src="{% static 'images/animals/image3.jpg' %}">
    <img src="{% static 'images/animals/image5.jpg' %}">
    <img src="{% static 'images/animals/image6.jpg' %}">
    <img src="{% static 'images/animals/image7.jpg' %}">
    <img src="{% static 'images/animals/image8.jpg' %}">
    <img src="{% static 'images/animals/image9.jpg' %}">
    <img src="{% static 'images/animals/image18.jpg' %}">
    <img src="{% static 'images/animals/image11.jpg' %}">
    <img src="{% static 'images/animals/image12.jpg' %}">
    <img src="{% static 'images/animals/image10.jpg' %}">
    <img src="{% static 'images/animals/image16.jpg' %}">
    <img src="{% static 'images/animals/image17.jpg' %}">






  </div>
  </div>
  <div id="mystocktext">



  <div class="container">
  <br>
  <br>
  <p></p>
  <p></p>

  <h1 id="hello" >MY STOCK</h1>

  </div>

  <h3 id='addontext'>THE <span id="future">FUTURE</span> STARTS TODAY!</h3>
    </div>
      </div>
      <div class="loader">
      <span class="loader-block"></span>
      <span class="loader-block"></span>
      <span class="loader-block"></span>
      <span class="loader-block"></span>
      <span class="loader-block"></span>
      <span class="loader-block"></span>
      <span class="loader-block"></span>
      <span class="loader-block"></span>
      <span class="loader-block"></span>
    </div>




 </body>
</html>

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>My Stock</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,700|Merriweather' rel='stylesheet' type='text/css'>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Teko:wght@600&display=swap" rel="stylesheet">
    <script src="{% static 'js/blog.js' %}">

    </script>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index' %}"> <span id="my">My</span> Stock</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'admin:index' %}">Admin <span class="sr-only"></span></a></li>
        <li><a href="{% url 'blog:users' %}">Feedback</a></li>
        <li><a href="{% url 'blog:register' %}">Register</a></li>
        <li><a href="{% url 'blog:about' %}">About</a></li>



      </ul>
      <ul class="nav navbar-nav navbar-right">


        {% if user.is_authenticated %}
        <li><a href="{% url 'logout' %}"><span id="username">{{ user.username }} </span>   Logout</a></li>
        {% else %}
        <li><a href="{% url 'blog:user_login' %}"><span id="login">Login</span></a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{% block body_block %}
{% endblock %}


  <br>
  <br>
  <br>
  <br>
<div class="back">
  <img class="iphoneback" src="{% static 'images/home/back.jpg' %}" alt="">

</div>

<div class="container">

<div id ="addimg">


<form class="input group" role="search">
<div class="pull-left">
<input id="searchbar" type="text" class="form-control" placeholder="Search Photos">
</div>
<button id = "searchbtn" type="Search" class="btn btn-default navbarbtn">Search</button>

</form>
</div>
</div>
<br>
<br>
<br>
<br>
<br><br><br>
<div class = "exploretxt">
      <h1>Explore the world arround you<span id = 'explore'></span>!</h1>
      <h4>“Photography takes an instant out of time, altering life by holding it still.”
</h4>

</div>
<div id = "freesub">



<form class="navbar navbar-inverse" role="search">
  <div class="form-group">

  </div>
  <div id="subtext">



  </div>
</form>
</div>
<h2 id= "collect">Featured <span id = 'explore'>Stock </span>Photo collection</h2>

<div class="view view-first">
  <img src="{% static 'images/home/image41.jpg' %}" />
  <div class="mask">
    <h2>Earth Day</h2>
    <p>: the physical world and everything in it (such as plants, animals, mountains, oceans, stars, etc.) that is not made by people..</p>
    {% if user.is_authenticated %}
    <a href="{% url 'blog:earth' %}" height="500" width="435" class="info">VIEW MORE</a>
    {% else %}
    <a href="{% url 'blog:user_login' %}"><span id="login">Login to view</span></a>
    {% endif %}  </div>
</div>


</div>
</form>
</div>
<div class="view view-first">
<img src="{% static 'images/home/phone.jpg' %}" />
<div class="mask">
  <h2>MACRO</h2>
  <p>:Close-up photography of small subjects, including things like bugs and flowers.</p>
  {% if user.is_authenticated %}
  <a href="{% url 'blog:macro' %}" height="500" width="435" class="info">VIEW MORE</a>
  {% else %}
  <a href="{% url 'blog:user_login' %}"><span id="login">Login to view</span></a>
  {% endif %}
</div>
</div>

<div class="view view-first">
<img src="{% static 'images/home/templeFV.jpg' %}" />
<div class="mask">
  <h2>Architecture</h2>
  <p>A cool description of some sort between these tags. I am so cool and awesomely awesome.</p>
  {% if user.is_authenticated %}
  <a href="{% url 'blog:archi' %}" height="500" width="435" class="info">VIEW MORE</a>
  {% else %}
  <a href="{% url 'blog:user_login' %}"><span id="login">Login to view</span></a>
  {% endif %}</div>
</div>
<div class="view view-first">
<img src="{% static 'images/home/landscape2.jpg' %}" />
<div class="mask">
  <h2>animals</h2>
  <p>:capturing images of animals for use in commercial and artistic endeavors..</p>
  {% if user.is_authenticated %}
  <a href="{% url 'blog:animals' %}" height="500" width="435" class="info">VIEW MORE</a>
  {% else %}
  <a href="{% url 'blog:user_login' %}"><span id="login">Login to view</span></a>
  {% endif %}
</div>
</div>



<div class="view view-first">
<img src="{% static 'images/home/parachu3.jpg' %}" />
<div class="mask">
  <h2>travel</h2>
  <p>:This includes anything from digital editing, altering darkroom developments, playing with camera settings or usage or making Art Collages.</p>
  {% if user.is_authenticated %}
  <a href="{% url 'blog:travel' %}" height="500" width="435" class="info">VIEW MORE</a>
  {% else %}
  <a href="{% url 'blog:user_login' %}"><span id="login">Login to view</span></a>
  {% endif %}</div>
</div>

<div class="view view-first">
<img src="{% static 'images/home/falls.jpg' %}" />
<div class="mask">
  <h2>LOng exposure</h2>

  {% if user.is_authenticated %}
  <a href="{% url 'blog:long' %}" height="500" width="435" class="info">VIEW MORE</a>
  {% else %}
  <a href="{% url 'blog:user_login' %}"><span id="login">Login to view</span></a>
  {% endif %}</div>
</div>

<div class="view view-first">
<img src="{% static 'images/home/curve.jpg' %}" />
<div class="mask">
  <h2>Roads</h2>
  <p>:Long-exposure photography involves using a long-duration shutter speed to sharply capture the stationary elements</p>
  {% if user.is_authenticated %}
  <a href="{% url 'blog:roads' %}" height="500" width="435" class="info">VIEW MORE</a>
  {% else %}
  <a href="{% url 'blog:user_login' %}"><span id="login">Login to view</span></a>
  {% endif %}</div>
</div>

<div class="view view-first">
<img src="{% static 'images/home/beach.jpg' %}" />
<div class="mask">
  <h2>Experimental</h2>
  <p>:Long-exposure photography involves using a long-duration shutter speed to sharply capture the stationary elements</p>
  {% if user.is_authenticated %}
  <a href="{% url 'blog:experiment' %}" height="500" width="435" class="info">VIEW MORE</a>
  {% else %}
  <a href="{% url 'blog:user_login' %}"><span id="login">Login to view</span></a>
  {% endif %}</div>
</div>
<br>
<h1></h1>

<br>
<div class="container">
<br>
<br>
<p></p>
<p></p>


<h1 id="hello" >MY STOCK</h1>
</div>
<h3 id='addontext'>THE <span id="future">FUTURE</span> STARTS TODAY!</h3>




<div class="centerer">


  <div class="wrap">
    {% if user.is_authenticated %}
    <a class="btn-0" href="{% url 'blog:animals' %}" style= "text-decoration: none;">Animals</a>
    {% else %}
    <a class="btn-0" href="" style= "text-decoration: none;">Animals</a>

    {% endif %}

  </div>


</div>
<div class="centerer1">
  <div class="wrap1">
    {% if user.is_authenticated %}
    <a class="btn-1" href="{% url 'blog:macro' %}" style= "text-decoration: none;">Macro</a>
    {% else %}
    <a class="btn-1" href="" style= "text-decoration: none;">Macro</a>
    {% endif %}
    </div>
    </div>
    </div>




<div class="centerer2">
  <div class="wrap2">
    {% if user.is_authenticated %}
    <a class="btn-3" href="{% url 'blog:archi' %}" style= "text-decoration: none;">Architecture</a>
    {% else %}
    <a class="btn-3" href="" style= "text-decoration: none;">Architecture</a>
    {% endif %}
  </div>
  </div>
</div>
<div class="centerer3">
  <div class="wrap3">
    {% if user.is_authenticated %}
    <a class="btn-3" href="{% url 'blog:experiment' %}" style= "text-decoration: none;">Experimental</a>
    {% else %}
    <a class="btn-3" href="" style= "text-decoration: none;">Experimental</a>
    {% endif %}
  </div>
  </div>
  <div class="centerer4">
    <div class="wrap4">
      {% if user.is_authenticated %}
      <a class="btn-4" href="{% url 'blog:travel' %}" style= "text-decoration: none;">Travel</a></div>
      {% else %}
      <a class="btn-4" href="" style= "text-decoration: none;">Travel</a></div>
      {% endif %}
    </div>
    <div class="centerer5">
      <div class="wrap5">
        {% if user.is_authenticated %}
        <a class="btn-5" href="{% url 'blog:roads' %}" style= "text-decoration: none;">Roads</a></div>
        {% else %}
        <a class="btn-5" href="" style= "text-decoration: none;">Roads</a></div>
        {% endif %}
      </div>









  </body>
</html>

blog/templates/blog/index.html
{% extends "blog/base.html" %}
{% block body_block %}

<div class="container">
    {% if user.is_authenticated %}
        <ul class="nav navbar-nav">
          <li><span class="sr-only"></span></li>
    {% else %}
    <ul class="nav navbar-nav">
      <li><span class="sr-only"></span></li>

    {% endif %}
  </div>

{% endblock %}